### ISSUE TITLE
Dev: 加入讀寫 cache 層

### ISSUE THREAD

**Issue by iamcxa** [iamcxa/sails-hook-sequelize-querier#8]
# Development

- https://www.notion.so/weo/2dec891a76cd4d53a19357a1e4369702?v=249402747a3848739d568358adf03dd5&p=79c8e74cbb2a498ca9258c4a401560e1
- 基於 [DanielHreben/sequelize-transparent-cache: Simple to use and universal cache layer for Sequelize](https://github.com/DanielHreben/sequelize-transparent-cache#readme)
- 目標是用來作為 sails-hook-messenger 的基礎，處理短時間內的大量讀寫

已知問題 - 可能需要修復
- [The dataToInstance method is very performance-consuming · Issue #84 · DanielHreben/sequelize-transparent-cache](https://github.com/DanielHreben/sequelize-transparent-cache/issues/84)
- [Literal expression doesn't work · Issue #81 · DanielHreben/sequelize-transparent-cache](https://github.com/DanielHreben/sequelize-transparent-cache/issues/81)
- [TypeError: instance.get is not a function (when using "raw: true" with findAll) · Issue #80 · DanielHreben/sequelize-transparent-cache](https://github.com/DanielHreben/sequelize-transparent-cache/issues/80)
- [Unable to cache the data in Redis using cache().create() · Issue #76 · DanielHreben/sequelize-transparent-cache](https://github.com/DanielHreben/sequelize-transparent-cache/issues/76)
- [findAndCountAll not working · Issue #75 · DanielHreben/sequelize-transparent-cache](https://github.com/DanielHreben/sequelize-transparent-cache/issues/75)
- [Cache include query not possible ? · Issue #61 · DanielHreben/sequelize-transparent-cache](https://github.com/DanielHreben/sequelize-transparent-cache/issues/61)

# Acceptance criteria

- [x] CRUD + getpaging 支援 cache
- [x] 支援 read/write cach
- [x] 測試同時讀寫 10000 筆效能
- [x] 搭配 Transaction 使用驗證（成功寫入/失敗rollback）
- [x] 簡易文件 - 說明如何使用與範例

# Before Hands-on Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria and developing goal 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified
